version: '3.3'
volumes:
  pg-data:
services:
  book-shop-db:
    container_name: book-shop-db
    image: postgres:18.1
    environment:
      POSTGRES_DB: book-shop
      POSTGRES_USER: pssoftware
      POSTGRES_PASSWORD: pssoftware
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro