version: "3.9"
volumes:
  postgres-data:
services:
  book-shop-db:
    container_name: book-shop-db
    image: postgres:18.1
    environment:
      POSTGRES_DB: book-shop
      POSTGRES_USER: pssoftware
      POSTGRES_PASSWORD: pssoftware
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./src/main/resources/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro