spring.application.name=book-store-api

spring.datasource.url=jdbc:postgresql://localhost:5432/book-shop
spring.datasource.username=pssoftware
spring.datasource.password=pssoftware
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true